// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4m7D_Wl5dpEC1LsSmr0D3AoRiV137BkM',
    appId: '1:52839296141:web:da1a7574d5c2c5587e86c4',
    messagingSenderId: '52839296141',
    projectId: 'aifashion-1f090',
    authDomain: 'aifashion-1f090.firebaseapp.com',
    storageBucket: 'aifashion-1f090.firebasestorage.app',
    measurementId: 'G-SNK5ZNJ86R',
    databaseURL: 'https://aifashion-1f090-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNlGPbkgQESeyVHOk46Al_l8I7JEyCVbk',
    appId: '1:52839296141:android:3e24d4ef50f58df67e86c4',
    messagingSenderId: '52839296141',
    projectId: 'aifashion-1f090',
    storageBucket: 'aifashion-1f090.firebasestorage.app',
    databaseURL: 'https://aifashion-1f090-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKkfXd4cHhJLnrQ3-Nx-RYid7YAnbZb1Y',
    appId: '1:52839296141:ios:cd4f76797a7361097e86c4',
    messagingSenderId: '52839296141',
    projectId: 'aifashion-1f090',
    storageBucket: 'aifashion-1f090.firebasestorage.app',
    iosBundleId: 'com.example.stylesync',
    databaseURL: 'https://aifashion-1f090-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKkfXd4cHhJLnrQ3-Nx-RYid7YAnbZb1Y',
    appId: '1:52839296141:ios:cd4f76797a7361097e86c4',
    messagingSenderId: '52839296141',
    projectId: 'aifashion-1f090',
    storageBucket: 'aifashion-1f090.firebasestorage.app',
    iosBundleId: 'com.example.stylesync',
    databaseURL: 'https://aifashion-1f090-default-rtdb.firebaseio.com/'
  );
}
